# Generated by Django 3.1.3 on 2020-11-23 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'customers'},
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
